- app/src/main/AndroidManifest.xml
- app/src/main/java/fi/razerman/youtube/Autorepeat/AutoRepeat.java
- app/src/main/java/fi/razerman/youtube/Fenster/Helpers/BrightnessHelper.java
- app/src/main/java/fi/razerman/youtube/Fenster/Seekbar/BrightnessSeekBar.java
- app/src/main/java/fi/razerman/youtube/Helpers/ColorRef.java
- app/src/main/java/fi/razerman/youtube/VideoUrl/Copy.java
- app/src/main/java/fi/razerman/youtube/VideoUrl/CopyWithTimeStamp.java
- app/src/main/java/fi/razerman/youtube/XAdRemover.java
- app/src/main/java/fi/razerman/youtube/XDebug.java
- app/src/main/java/fi/razerman/youtube/XGlobals.java
- app/src/main/java/fi/razerman/youtube/XJson.java
- app/src/main/java/fi/razerman/youtube/XReboot.java
- app/src/main/java/fi/razerman/youtube/XSettingActivity.java
- app/src/main/java/fi/razerman/youtube/XSettingsFragment.java
- app/src/main/java/fi/razerman/youtube/XTheme.java
- app/src/main/java/fi/razerman/youtube/videosettings/VideoSpeed.java
- Removed redundant values.
- Removed boolean value unboxing.
- Unwrapped unnecessary if statements.
- There are errors since there are YouTube code references.
> chore: refactor code

- app/src/main/java/fi/razerman/youtube/XAdRemover.java
Not sure what the contribution process is on this repository, but I found a typo in the ad-remover integration. Fixed in this PR.
> Fixed typo: `hierarcy` -> `hierarchy`

- app/build.gradle
Refactor `applicationId` from `revanced.integrationspp` to `revanced.integrationsapp`.
> refactor: rename applicationId

- app/src/main/java/app/revanced/integrations/adremover/LithoAdRemoval.java
https://github.com/revanced/revanced-patches/issues/109
> 'Suggested for you' block

- app/src/main/java/app/revanced/integrations/adremover/LithoAdRemoval.java
> Alphabetical reorder

- app/src/main/java/app/revanced/integrations/adremover/whitelist/Whitelist.java
Fixes #52 and [revanced/revanced-cli#82](https://github.com/revanced/revanced-cli/issues/82)
> fix: Fix NPE when opening video from different App

- app/src/main/java/app/revanced/integrations/fenster/util/SwipeControlZoneHelper.kt
enable skip button by reducing padding dpi.
> fix: Reduce padding DPI for swipe zones

- app/src/main/java/app/revanced/integrations/fenster/controllers/FensterOverlayController.kt
change overlay time to 250ms or 500ms for fast volume & brightness panel switch. Also 2sec is iritating.
> fix: change overlay time of swipe-controls

- app/src/main/java/app/revanced/integrations/adremover/LithoAdRemoval.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/utils/LogHelper.java
> fix: use Log.d for debugging

- app/src/main/java/app/revanced/integrations/patches/HDRMaxBrightnessPatch.java
- app/src/main/java/app/revanced/integrations/patches/SwipeControlsPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingsFragment.java
- app/src/main/java/app/revanced/integrations/swipecontrols/controller/ScreenBrightnessController.kt
- app/src/main/res/values/strings.xml
closes https://github.com/revanced/revanced-patches/issues/150
> fix: `hdr-auto-brightness`

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> feat: added issue templates.

- app/src/main/java/app/revanced/integrations/patches/OldQualityLayoutPatch.java
> fix: cleanup `old-quality` patch

- app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingsFragment.java
- app/src/main/java/com/google/android/apps/youtube/app/application/Shell_HomeActivity.java
has to be merged together with patches pr:
- https://github.com/revanced/revanced-patches/pull/260
> fix: app crashes on reboot

- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingsFragment.java
Force codec feature was removed but the settings corresponding to it was not
> Remove stray codec settings

- app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
Partially fixes
- #118 
will continue to work on the old layout but at least the likes on the new one won't get overwritten.
> fix: unintentional like button detection

- app/src/main/java/app/revanced/integrations/patches/GeneralBytecodeAdsPatch.java
- app/src/main/java/app/revanced/integrations/patches/HideCreateButtonPatch.java
- app/src/main/java/app/revanced/integrations/patches/HideHomeAdsPatch.java
- app/src/main/java/app/revanced/integrations/patches/NewActionbarPatch.java
- app/src/main/java/app/revanced/integrations/patches/VideoAdsPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingActivity.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingsFragment.java
RE:  https://github.com/revanced/revanced-patches/issues/158
Depends on:
- https://github.com/revanced/revanced-patches/pull/266
> feat: `settings` patch framework 

- app/src/main/java/app/revanced/integrations/patches/GeneralBytecodeAdsPatch.java
Still need to be tested further, to be sure it always works.
> fix: pull up to refresh

- app/src/main/java/app/revanced/integrations/patches/GeneralBytecodeAdsPatch.java
Reverts revanced/revanced-integrations#129
> fix: revert "pull up to refresh"

- app/build.gradle.kts
- app/proguard-rules.pro
Increases merging speeds by decreasing the amount of kotlin classes.
> feat: enable minification 

- app/src/main/java/app/revanced/integrations/patches/HideEmailAddressPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
RE: https://github.com/revanced/revanced-patches/pull/578
> feat: hide settings email address

- app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRequester.java
no clue why github keeps adding the newline but I can't get rid of it.
> fix(SB): 400 on submitting prints an object

- app/src/main/java/app/revanced/integrations/sponsorblock/player/VideoHelpers.java
- app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/SkipSponsorButton.java
minSdk already at 23 so we don't need hacks for older ones.
> perf: remove obsolete SDK checks

- app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
- app/src/main/java/app/revanced/integrations/sponsorblock/SponsorBlockSettings.java
- app/src/main/java/app/revanced/integrations/sponsorblock/objects/SponsorSegment.java
> Change that auto skipped will only trigger once per segment

- app/src/main/java/app/revanced/integrations/patches/OpenLinksDirectlyPatch.java
- app/src/main/java/app/revanced/integrations/patches/UriRedirectPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
Depends on:
- https://github.com/revanced/revanced-patches/pull/999
> feat(YouTube): URI-redirect-patch

- app/src/main/java/app/revanced/integrations/patches/LithoThemePatch.java
Closes: https://github.com/revanced/revanced-patches/issues/922
> fix(youtube/theme): shorts comment box color

- app/src/main/java/app/revanced/integrations/patches/LithoFilterPatch.java
> fix(youtube/general-ads-patch): save playlist exclusion

- app/src/main/java/app/revanced/integrations/patches/LithoThemePatch.java
https://www.reddit.com/r/revancedapp/comments/ypt7ii/black_theme_doesnt_get_applied_here_in_the/
> feat(youtube/theme): explore drawer background

- app/src/main/java/app/revanced/twitch/patches/AudioAdsPatch.java
- app/src/main/java/app/revanced/twitch/patches/DebugModePatch.java
- app/src/main/java/app/revanced/twitch/patches/ShowDeletedMessagesPatch.java
- app/src/main/java/app/revanced/twitch/patches/VideoAdsPatch.java
After all those PRs, I got confused and somehow forgot to commit a few required changes for the patch updates. :sweat_smile:
> fix(twitch): add missing classes

- app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
- app/src/main/java/app/revanced/integrations/returnyoutubedislike/requests/RYDVoteData.java
- app/src/main/java/app/revanced/integrations/returnyoutubedislike/requests/ReturnYouTubeDislikeApi.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReturnYouTubeDislikeSettingsFragment.java
Integration changes needed for 
https://github.com/revanced/revanced-patches/pull/1185
> Option to show dislikes as a percentage of total votes

- app/build.gradle.kts
- app/src/main/java/app/revanced/twitch/adblock/IAdblockService.kt
- app/src/main/java/app/revanced/twitch/adblock/PurpleAdblockService.kt
- app/src/main/java/app/revanced/twitch/adblock/TTVLolService.kt
- app/src/main/java/app/revanced/twitch/api/PurpleAdblockApi.java
- app/src/main/java/app/revanced/twitch/api/RequestInterceptor.kt
- app/src/main/java/app/revanced/twitch/api/RetrofitClient.java
- app/src/main/java/app/revanced/twitch/patches/EmbeddedAdsPatch.java
- app/src/main/java/app/revanced/twitch/settings/SettingsEnum.java
- app/src/main/java/app/revanced/twitch/utils/LogHelper.java
- app/src/main/java/app/revanced/twitch/utils/ReVancedUtils.java
Depends on:
- https://github.com/revanced/revanced-patcher/issues/126
(cherry picked from commit 00ea006b8c2e395ba56e8e5b90c467542849be46)
> feat(twitch): `block-embedded-ads` patch support

- app/src/main/java/app/revanced/integrations/adremover/AdRemoverAPI.java
it sames work maybe. because view.setLayoutParams's parameter is ViewGroup.Layout Params.
but i'm poor at andriod and it's inner logic.
ps.
I want to contribute other revanced projects. can i help you?
> refactor : AdRemoverAPI.HideViewWithLayout1dp in my opnion

- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
Fixed oversight of the migration code.
> Fixed incorrect migration of renamed settings

- app/src/main/java/app/revanced/integrations/adremover/AdRemoverAPI.java
Reverts revanced/revanced-integrations#240
Fixes revanced/revanced-patches/issues/1331
> fix: revert semantically incorrect simplification of ˋAdRemoverAPI.HideViewWithLayout1dpˋ

- app/src/main/java/app/revanced/integrations/videoplayer/DownloadButton.java
refactor : if statement optimizing
i will reduce this field
tell me field that will use
> refactor DownloadButton

- app/build.gradle.kts
- build.gradle.kts
- dummy/build.gradle.kts
- settings.gradle.kts
This PR refactors build related files and names output files.
> build: name output files

- app/src/main/java/app/revanced/integrations/videoplayer/BottomControlButton.java
remove getIdenfiter method, and use RevanceUtils mehod
https://github.com/revanced/revanced-suggestions/discussions/857
> refactor : remove getIdentifier method

- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/utils/SharedPrefHelper.java
Signed-off-by: oSumAtrIX <johan.melkonyan1@web.de>
> fix: load numeric preferences as type String

- app/src/main/java/app/revanced/all/screenshot/removerestriction/RemoveScreenshotRestrictionPatch.java
related patches PR: https://github.com/revanced/revanced-patches/pull/1455
> feat: no screenshot block patch

- app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReturnYouTubeDislikeSettingsFragment.java
- app/src/main/java/app/revanced/integrations/utils/ReVancedUtils.java
integration changes for https://github.com/revanced/revanced-patches/pull/1454
> feat(YouTube): ReturnYouTubeDislike compact like button layout

- app/src/main/java/app/revanced/integrations/patches/MicroGSupport.java
Implemets a check to check if Vanced MicroG is running or not and if it's not running, it'll open the Don't Kill My App guide and show a toast.
> feat(youtube/microg-support): check if microg is running

- app/src/main/java/app/revanced/integrations/patches/PlayerTypeHookPatch.java
- app/src/main/java/app/revanced/integrations/patches/ReturnYouTubeDislikePatch.java
- app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
- app/src/main/java/app/revanced/integrations/shared/PlayerType.kt
- app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
Integration changes for https://github.com/revanced/revanced-patches/pull/1532
> fix(YouTube) ReturnYouTubeDislike shorts voting fix

- app/src/main/java/app/revanced/integrations/patches/GeneralAdsPatch.java
- app/src/main/java/app/revanced/integrations/patches/HideCreateButtonPatch.java
- app/src/main/java/app/revanced/integrations/patches/HideShortsButtonPatch.java
- app/src/main/java/app/revanced/integrations/patches/MicroGSupport.java
- app/src/main/java/app/revanced/integrations/patches/VideoInformation.java
- app/src/main/java/app/revanced/integrations/patches/playback/quality/RememberVideoQualityPatch.java
- app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
- app/src/main/java/app/revanced/integrations/returnyoutubedislike/requests/ReturnYouTubeDislikeApi.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingActivity.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingsFragment.java
- app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
- app/src/main/java/app/revanced/integrations/sponsorblock/ShieldButton.java
- app/src/main/java/app/revanced/integrations/sponsorblock/SkipSegmentView.java
- app/src/main/java/app/revanced/integrations/sponsorblock/SponsorBlockUtils.java
- app/src/main/java/app/revanced/integrations/sponsorblock/StringRef.java
- app/src/main/java/app/revanced/integrations/sponsorblock/SwipeHelper.java
- app/src/main/java/app/revanced/integrations/sponsorblock/VotingButton.java
- app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/SlimButton.java
- app/src/main/java/app/revanced/integrations/sponsorblock/player/ui/SponsorBlockView.java
- app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRequester.java
- app/src/main/java/app/revanced/integrations/swipecontrols/controller/AudioVolumeController.kt
- app/src/main/java/app/revanced/integrations/utils/LogHelper.java
- app/src/main/java/app/revanced/integrations/utils/ReVancedUtils.java
- app/src/main/java/app/revanced/integrations/videoplayer/DownloadButton.java
- app/src/main/java/app/revanced/tiktok/utils/LogHelper.java
- app/src/main/java/app/revanced/twitch/utils/LogHelper.java
Integration changes for https://github.com/revanced/revanced-patches/pull/1511
Display a toast if a ReVanced error occurs.
This includes normal and common exceptions (RYD or SponsorBlock connection timeout), but also includes showing a toast for all other exceptions (real problems that should never occur).
This should help users figure out when something is wrong, and will give more information to report instead of posting a screen shot of an empty black screen with a comment of: "it don't work. I don't know."
> feat(YouTube) show toast on ReVanced error

- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
integration changes for https://github.com/revanced/revanced-patches/pull/1550
> fix(YouTube) error when switching on/off interaction setting

- app/src/main/java/app/revanced/all/connectivity/wifi/spoof/SpoofWifiPatch.java
Related patches PR: [revanced-patches#1527](https://github.com/revanced/revanced-patches/pull/1527)
> feat: spoof-wifi-connection patch

- app/src/main/java/app/revanced/integrations/patches/GeneralAdsPatch.java
> fix(YouTube/GeneralAds): `chapter's teaser` not hidden

- app/src/main/java/app/revanced/integrations/patches/HideLoadMoreButtonPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
RE: revanced/revanced-patches/pull/2078
> feat(youtube): `hide-load-more-button` patch

- app/src/main/java/app/revanced/integrations/patches/HidePlayerOverlayPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
RE: https://github.com/revanced/revanced-patches/pull/2044
TODO:
> feat(youtube/hide-player-overlay): make it toggleable in settings

- app/src/main/java/app/revanced/twitch/patches/AutoClaimChannelPointsPatch.java
- app/src/main/java/app/revanced/twitch/settings/SettingsEnum.java
Related to: https://github.com/revanced/revanced-patches/pull/2131
> Add setting for twitch/chat/autoclaim

- app/src/main/java/app/revanced/integrations/patches/SeekbarTappingPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/sponsorblock/SegmentPlaybackController.java
- app/src/main/java/app/revanced/integrations/utils/ThemeHelper.java
This PR bumps YouTube patches compatibility to `18.19.35`. It is ready to be merged by rebase as it contains multiple changes, remotely, but still required for the bump.
> feat(youtube): bump compatibility to `18.19.35`

- app/src/main/java/app/revanced/reddit/patches/SanitizeUrlQueryPatch.java
Related to https://github.com/revanced/revanced-patches/pull/2192
> feat(reddit): add `sanitize-sharing-links` patch

- app/src/main/java/app/revanced/reddit/patches/FilterPromotedLinksPatch.java
- dummy/src/main/java/com/reddit/domain/model/ILink.java
Tied to https://github.com/revanced/revanced-patches/pull/2350
> Added filterChildren method for reddit ad removal

- app/src/main/java/app/revanced/integrations/patches/components/LithoFilterPatch.java
No need to compute the failure function if not data is present!
> fix: make indexOf return earlier

- app/src/main/java/app/revanced/tiktok/settingsmenu/SettingsMenu.java
https://github.com/ReVanced/revanced-patches/pull/2656
> fix(tiktok/settings): fix settings patch

- app/src/main/java/app/revanced/integrations/patches/SpoofSignatureVerificationPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
integration changes for https://github.com/revanced/revanced-patches/pull/2607
> fix(youtube/spoof-signature-verification): show video time and chapters while using seekbar

- app/src/main/java/app/revanced/integrations/patches/components/ShortsFilter.java
closes: [#2754](https://github.com/ReVanced/revanced-patches/issues/2754)
> fix(YouTube - Hide Shorts components): Hide `shorts header`

- app/src/main/java/app/revanced/integrations/patches/OpenLinksExternallyPatch.java
Depends on https://github.com/ReVanced/revanced-patches/pull/2874
> feat(YouTube): Support version 18.32.39

- app/src/main/java/app/revanced/tudortmund/lockscreen/ShowOnLockscreenPatch.java
Integration changes for https://github.com/ReVanced/revanced-patches/pull/2947
> feat(TU Dortmund): Add `Show on lockscreen` patch

- app/src/main/java/app/revanced/integrations/patches/ReturnYouTubeDislikePatch.java
- app/src/main/java/app/revanced/integrations/patches/components/LithoFilterPatch.java
- app/src/main/java/app/revanced/integrations/patches/components/ShortsFilter.java
- app/src/main/java/app/revanced/integrations/patches/spoof/requests/StoryboardRendererRequester.java
- app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
Depends on https://github.com/ReVanced/revanced-patches/pull/3028
> feat(YouTube): Bump compatibility to `18.37.36`

- app/src/main/java/app/revanced/integrations/patches/VideoInformation.java
- app/src/main/java/app/revanced/integrations/patches/spoof/SpoofSignaturePatch.java
integration changes for https://github.com/ReVanced/revanced-patches/pull/3038
> fix(YouTube - Video Id): Fix video id not showing the currently playing video

- app/src/main/java/app/revanced/integrations/patches/components/PlayerFlyoutMenuItemsFilter.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
depends on:
- ReVanced/revanced-patches/pull/3163
> fix(YouTube - Player flyout menu): Restore functionality

- app/src/main/java/app/revanced/all/screenshot/removerestriction/RemoveScreenshotRestrictionPatch.java
patches: https://github.com/ReVanced/revanced-patches/pull/2938
> fix(Remove screenshot restriction): Improve reliability

- app/src/main/java/app/revanced/integrations/patches/components/AdsFilter.java
- app/src/main/java/app/revanced/integrations/patches/components/LayoutComponentsFilter.java
closes: 
- ReVanced/revanced-patches/issues/7
> fix(YouTube - Hide ads): Hide new type of ad

- app/src/main/java/app/revanced/integrations/youtube/patches/WideSearchbarPatch.java
Integrations for https://github.com/ReVanced/revanced-patches/pull/2656
> fix(YouTube): Correctly show channel page on tablet devices

- app/src/main/java/app/revanced/integrations/youtube/patches/spoof/SpoofSignaturePatch.java
> fix(Spoof Player Parameter): Playback issues appears when opening a YouTube link

- app/src/main/java/app/revanced/integrations/youtube/patches/GmsCoreSupport.java
- app/src/main/java/app/revanced/integrations/youtube/patches/spoof/SpoofSignaturePatch.java
- app/src/main/java/app/revanced/integrations/youtube/patches/spoof/StoryboardRenderer.java
- app/src/main/java/app/revanced/integrations/youtube/patches/spoof/requests/PlayerRoutes.java
- app/src/main/java/app/revanced/integrations/youtube/patches/spoof/requests/StoryboardRendererRequester.java
RE: https://github.com/ReVanced/revanced-patches/pull/2907
> fix(YouTube): Fix video playback by switching to ReVanced GmsCore vendor

- app/src/main/java/app/revanced/integrations/shared/GmsCoreSupport.java
Some browsers would fail to treat links properly when opened as a query and launch a web search.
> feat: Open links without query if possible

- app/src/main/java/app/revanced/integrations/youtube/patches/components/DescriptionComponentsFilter.java
- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
https://github.com/ReVanced/revanced-patches/pull/3327
> fix(YouTube - Hide description components): Replace `Hide game section` and `Hide music section` with `Hide attributes section`

- app/src/main/java/app/revanced/integrations/youtube/patches/spoof/SpoofClientPatch.java
- stub/src/main/java/org/chromium/net/ExperimentalUrlRequest.java
Integrations for: [ReVanced/revanced-patches#3468](https://github.com/ReVanced/revanced-patches/pull/3468)
> fix(YouTube - Client Spoof): Unlock more qualities by spoofing the iOS client user agent 

- app/src/main/java/app/revanced/integrations/youtube/patches/components/DescriptionComponentsFilter.java
- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
https://github.com/ReVanced/revanced-patches/pull/3486
> feat(YouTube - Description components): Add  `Hide 'Key concepts' section` option

- app/src/main/java/app/revanced/integrations/youtube/patches/components/LayoutComponentsFilter.java
fixes https://github.com/ReVanced/revanced-patches/issues/3563
> fix(YouTube - Hide layout components): Hide new kind of community post

- app/src/main/java/app/revanced/integrations/youtube/patches/components/ShortsFilter.java
- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
Integrations for https://github.com/ReVanced/revanced-patches/pull/3647
> feat(YouTube - Hide Shorts components): Hide 'Use this sound' button

- app/src/main/java/app/revanced/integrations/youtube/patches/components/ShortsFilter.java
- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
Integrations for https://github.com/ReVanced/revanced-patches/pull/3752
> feat(YouTube - Hide Shorts components): Add options to hide `Use template`, `Upcoming`, `Green screen` buttons
