ReVanced/revanced-integrations

- app/src/main/java/fi/razerman/youtube/litho/LithoAdRemoval.java
Not sure if this is even useful, but I noticed that the reimplementation of LithoAdRemoval.indexOf never increments the index for the outer loop, causing an infinite loop.
> fix: correct implementation of indexOf

- build.gradle
Summary: Add dummy task `publish`.
RE: #40
> fix: add missing dummy task `publish`

- app/src/main/java/app/revanced/integrations/fenster/controllers/FensterController.kt
vanced style swipe volume and brightness, no need to longpress. perfectly compatable with patches 2.9.1.
> fix: remove long-press from swipe-controls

- app/src/main/java/app/revanced/integrations/adremover/LithoAdRemoval.java
This addition extends the litho comment blockage on those videos, where a box is shown to warns you that comments are turned off.
It's just a consistency patch, to ensure that anything related to comments remains hidden, when the dedicated toggle on settings page is enabled.
> refactor: Litho comments blockage generalization

- README.md
- app/src/main/java/app/revanced/integrations/patches/GeneralBytecodeAdsPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
See tracking issue
- https://github.com/revanced/revanced-integrations/issues/84
> feat: block `channel-guidelines`. Fixes #84

- app/src/main/java/app/revanced/integrations/utils/SharedPrefHelper.java
Currently when you migrate ReVanced from non-settings variant to settings-variant the app crashes because sharedprefs are handled different now. This currently results in the need for clearing app data. This PR fixes this.
> fix: app crashes on first start

- app/src/main/java/app/revanced/integrations/patches/VideoAdsPatch.java
before: ads are shown only when video ads are enabled AND channel is whitelisted
(means without using the whitelist the ads toggle doesn't do anything, making it useless if you want to support all creators)
after: ads are shown when either video ads toggle is enabled OR channel is whitelisted
also format the comments
> fix: logic in `VideoAdsPatch`

- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
Toggling tablet miniplayer also requires a restart to work properly
> restart prompt for tablet miniplayer

- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
Toggling the downloads button needs a reboot too otherwise the button does not show/hide
> fix: downloads button needs reboot

- app/src/main/java/app/revanced/integrations/patches/GeneralBytecodeAdsPatch.java
Add `video_display_full_layout` to value blockList of LithoAd filter. Possibly fix https://github.com/revanced/revanced-patches/issues/432
> fix: add more block string to `LithoAd` filter

- app/src/main/java/app/revanced/integrations/patches/GeneralBytecodeAdsPatch.java
This is a different approach to ads blocking, and it's based on a simple concept:
"Don't block the template by its name, but by its link"
Every ad have at least one link, from which get the informations shown to the user, and this link have a unique pattern (3 in total, for all ad).
> fix: more generalized `litho ads`removal

- app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRequester.java
Users are coming into the SponsorBlock discord presenting error 400, which is a generic catch-all for inputs that are bad or impossible. This is usually a bad userID but eating the error makes troubleshooting extremely difficult when it's not.
Possible causes of 400
- userID
- videoID
- no segments
- invalid segment times
- descriptions on non-chapters
- chapters that exceed limit
- lack of permissions
> fix(sponsorblock): return details of 400 error

- app/src/main/java/app/revanced/integrations/swipecontrols/SwipeControlsHostActivity.kt
see https://github.com/revanced/revanced-patches/issues/446
merge of this PR should depend on project goals. 
This fix only affects devices with SDK <= 23, which are no longer supported by official youtube (min SDK was raised to 26 a while back).
> fix: `swipe-controls` crashing on SDK <= 23

- app/src/main/java/app/revanced/integrations/patches/LithoFilterPatch.java
This commit resolves this issue https://github.com/revanced/revanced-patches/issues/751
I tested it on 2 people and found that text banner ads were removed
> fix(youtube/general-ads): remove text banner ads

- app/src/main/java/app/revanced/integrations/settingsmenu/ReVancedSettingsFragment.java
- app/src/main/java/app/revanced/integrations/utils/ReVancedUtils.java
- app/src/main/java/com/google/android/apps/youtube/app/YouTubeTikTokRoot_Application.java
Reverts revanced/revanced-integrations#180 because it was marked as a refactor and did not trigger CI. A separate PR should the  revert this PR with a fix.
> fix: revert removing getAppContext()

- app/src/main/java/app/revanced/integrations/patches/LithoThemePatch.java
Reverts #202 due to https://github.com/revanced/revanced-patches/issues/1046 and opens https://github.com/revanced/revanced-patches/issues/922.
> fix(youtube/theme): revert shorts comment box coloring

- app/src/main/java/app/revanced/integrations/patches/GeneralAdsPatch.java
menu, root, count, space and button are child component names of comment_thread. There's no point in blocking them, because you can only block comment_thread.
> refactor(youtube/general-ads-patch): remove unused names

- app/src/main/java/app/revanced/integrations/patches/GeneralAdsPatch.java
"search_video_with_context" are accessible through the opening of the following components:
Meanwhile the component "|comment." exists only on comments replies, in place of "comment_thread".
> refactor(youtube/general-ads-patch): added new names

- app/src/main/java/app/revanced/integrations/requests/Requester.java
- app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
- app/src/main/java/app/revanced/integrations/returnyoutubedislike/requests/ReturnYouTubeDislikeApi.java
- app/src/main/java/app/revanced/integrations/returnyoutubedislike/requests/ReturnYouTubeDislikeRoutes.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReturnYouTubeDislikeSettingsFragment.java
- app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRequester.java
- app/src/main/java/app/revanced/integrations/utils/LogHelper.java
- app/src/main/java/app/revanced/integrations/utils/ReVancedUtils.java
I changed the background thread pool so all threads run at max priority.
This change seems to reduce the average time needed to load the video UI, as the RYD vote fetch now gets priority over other background threads (the fetch is blocking the UI, it definitely should get priority). 
Currently this thread pool is only used by RYD for the fetch votes calls.
> ReturnYouTubeDislike connection statistics. Show client toast messages on RYD connection errors.  High priority background threads.

- app/src/main/java/app/revanced/integrations/patches/GeneralAdsPatch.java
As I explained in a previous occasion, some of the current ignore list component names are totally useless. Today I tried to remove them from the list and are still visible.
This is the screenshot of the final result:
> fix(youtube/general-ads-patch): improved ignore list

- app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
The OnePlus changes pushed my Samsung and Google phones out of wack.
No set of ratios will be perfect for all devices, all we can get is good enough for most devices
Can you see if these changes looks ok on your device?
Here's what it this PR looks like on my end:
Google Pixel (with this PR):
Samsung (with this PR):
> fix(youtube/return-youtube-dislike): use manufacturer specific span styles

- .github/workflows/release.yml
- app/build.gradle.kts
This PR fixes mismatched released package name versions.
Specifically, replace "./gradlew build" with the gradle-semantic-release-plugin method.
"./gradlew build" task is executed after automatic rewriting of gradle.properties's version.
> build: fix release-package-name's version

- app/src/main/java/app/revanced/integrations/returnyoutubedislike/ReturnYouTubeDislike.java
I got a better match of the separator color.  This is about the best it's going to get.
> RYD: better color match of existing dark mode separator color

- app/src/main/java/app/revanced/integrations/patches/MicroGSupport.java
Fixes the Vanced MicroG check not showing a toast to make the user install Vanced MicroG
**Note: It still does not show a toast but it opens the download page for Vanced MicroG before crashing with this error:**
```
AndroidRuntime: FATAL EXCEPTION: yt-critical Thread #0
AndroidRuntime: Process: app.revanced.android.youtube, PID: 7179
AndroidRuntime: java.lang.SecurityException: Failed to find provider com.mgoogle.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
```
> fix: microg check not showing toast

- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
Fix for settings not persistently saving across app sessions.
This might help the RYD backend, as the client was creating a new RYD user on the first vote of every app session.
> fix(YouTube) settings enum fails to save non-boolean values

- app/src/main/java/app/revanced/integrations/patches/MicroGSupport.java
Minor adjustment, so the app gracefully closes instead of crashing.
If the app is allowed to crash, then on Samsung devices it gives 'recommendations' to put the app to sleep or uninstall. 
These changes are verified working as expected.
> fix(YouTube) Gracefully close app if MicroG is missing or not running

- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
- app/src/main/java/app/revanced/integrations/settingsmenu/ReturnYouTubeDislikeSettingsFragment.java
- app/src/main/java/app/revanced/integrations/settingsmenu/SponsorBlockSettingsFragment.java
- app/src/main/java/app/revanced/integrations/sponsorblock/PlayerController.java
- app/src/main/java/app/revanced/integrations/sponsorblock/SponsorBlockSettings.java
- app/src/main/java/app/revanced/integrations/sponsorblock/SponsorBlockUtils.java
- app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRequester.java
- app/src/main/java/app/revanced/integrations/sponsorblock/requests/SBRoutes.java
- app/src/main/java/app/revanced/integrations/utils/ReVancedUtils.java
- fixed importation of browser json settings (removed importation of non standard SB_LAST_VIP_CHECK)
- fixed user id always showing as empty string (prevented voting and user stats from working)
- fixed skip segment toast not working (settings activity was not passing some values into SettingEnum)
Everything appears to be working now.
Fixes revanced/revanced-patches/issues/1105, fixes revanced/revanced-patches/issues/1447.
> fix(YouTube/Sponsorblock) Fix import json settings.  Fix default userid showing as empty.  Fix skip segment toast not working.

- app/src/main/java/app/revanced/integrations/patches/GeneralAdsPatch.java
- app/src/main/java/app/revanced/integrations/settings/SettingsEnum.java
integration changes for https://github.com/revanced/revanced-patches/pull/2021
> feat(youtube/general-ads): hide multiple audio track button on video overlay

- app/src/main/java/app/revanced/integrations/patches/GeneralAdsPatch.java
It removes the `buy premium` banner but semi-transparent overlay is still there.
> fix(youtube/general-ads): remove broken ad filter

- app/src/main/java/app/revanced/integrations/patches/components/LayoutComponentsFilter.java
Also available in [AdsFilter](https://github.com/revanced/revanced-integrations/blob/170685b920de85133f33dfcc31bcc68eac3f6351/app/src/main/java/app/revanced/integrations/patches/components/AdsFilter.java#L58).
> fix(youtube/ads-filter): remove duplicate filter

- app/src/main/java/app/revanced/integrations/patches/components/ShortsFilter.java
> fix(YouTube - Hide Shorts components): Hide new type of shorts in feed

- app/src/main/java/app/revanced/integrations/videoplayer/ExternalDownloadButton.java
If there were spaces in the package name anywhere, revanced would show a toast saying that the package could not be found, ideally it should find it no matter if there are spaces in the package name or not. This fixes that.
As discussed in discord, ideally package names should be trimmed on settings save but there is currently no abstraction for settings (as far as i can reinterpret from that message).
> fix(YouTube/ExternalDownloads): Trim spaces from package

- app/src/main/java/app/revanced/tumblr/patches/TimelineFilterPatch.java
- dummy/src/main/java/com/tumblr/rumblr/model/TimelineObject.java
- dummy/src/main/java/com/tumblr/rumblr/model/TimelineObjectType.java
- dummy/src/main/java/com/tumblr/rumblr/model/Timelineable.java
Required for the new Tumblr TimelineFilterPatch.  
See https://github.com/ReVanced/revanced-patches/pull/3018
> refactor(Tumblr): Use a common filter patch

- app/src/main/java/app/revanced/integrations/patches/DisableSuggestedVideoEndScreenPatch.java
- app/src/main/java/app/revanced/integrations/patches/playback/quality/RestoreOldVideoQualityMenuPatch.java
- app/src/main/java/app/revanced/integrations/patches/playback/speed/CustomPlaybackSpeedPatch.java
Fixes https://github.com/ReVanced/revanced-patches/issues/3234.
> fix(YouTube): Prevent side effects from performing clicks manually

- app/src/main/java/app/revanced/integrations/youtube/patches/spoof/SpoofAppVersionPatch.java
- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
Integrations part of: https://github.com/ReVanced/revanced-patches/pull/2787
- Adjust the migration logic
- Change the default spoof target to 17.33.42
> feat(YouTube - Spoof app version): Add target versions

- app/src/main/java/app/revanced/integrations/youtube/patches/announcements/AnnouncementsPatch.java
- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
Previously, the entire announcement was hashed and compared with the locally saved hash. Sometimes announcements are fixed up, and that alters the hash, so instead, just compare the ID.
> fix(YouTube - Announcements): Only compare ID to not show same announcement after a fix-up

- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
Autoplay is only triggered if the end screen is shown. If it is dismissed, which happens if the patch is enabled, autoplay will be stopped.
> fix(YouTube - Disable suggested video end screen): Disable by default to fix autoplay issues

- app/src/main/java/app/revanced/integrations/youtube/patches/announcements/AnnouncementsPatch.java
- app/src/main/java/app/revanced/integrations/youtube/patches/announcements/requests/AnnouncementsRoutes.java
- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
The query parameter was introduced with the intention of being used in the future. It turns out that it is not necessary and can be removed therefor.
> chore: Remove unnecessary consumer parameter

- app/src/main/java/app/revanced/integrations/shared/Utils.java
Using this integration led to an error on my device. 
This PR fixes it by using the standard Regex from java instead of the kotlin version
> fix: Use Java instead of Kotlin Regex to improve reliability 

- app/src/main/java/app/revanced/integrations/shared/Utils.java
- app/src/main/java/app/revanced/integrations/youtube/patches/spoof/SpoofClientPatch.java
- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
This PR also changes the default client spoof to iOS, as the only side effect known now is that HDR is not working.
> fix(YouTube - Client spoof): Spoof iOS client model to fix various side effects

- app/src/main/java/app/revanced/integrations/youtube/patches/VideoInformation.java
Add integration code to support skipping segments while casted to a big screen device, by hooking the MDX director class to intercept object instances in order to be able to call the seekTo method, similar to how it's done in the 'regular' player class.
Fixes https://github.com/ReVanced/revanced-patches/issues/374.
Patches PR: https://github.com/ReVanced/revanced-patches/pull/3331
> fix(YouTube - SponsorBlock): Skip segments when casting

- app/src/main/java/app/revanced/integrations/shared/Utils.java
- app/src/main/java/app/revanced/integrations/youtube/patches/spoof/SpoofClientPatch.java
Integration changes for https://github.com/ReVanced/revanced-patches/pull/3504
> fix(YouTube - Spoof client): Restore livestream audio only playback with iOS spoofing

- app/src/main/java/app/revanced/integrations/youtube/patches/ReturnYouTubeDislikePatch.java
Some users report this A/B test:
The change does not affect users without the A/B test
> fix(YouTube - Return YouTube Dislike): Fix dislikes not appearing due to new component name

- app/src/main/java/app/revanced/integrations/youtube/patches/DisablePreciseSeekingGesturePatch.java
Integrations for: https://github.com/ReVanced/revanced-patches/pull/3668
> feat(YouTube - Disable precise seeking gesture): Hide "pull up" label that shows up when swiping

- app/src/main/java/app/revanced/integrations/youtube/patches/components/ShortsFilter.java
- app/src/main/java/app/revanced/integrations/youtube/settings/Settings.java
The ordering in code may be adjusted.
> feat(YouTube - Hide Shorts components): Add option to hide like fountain

- app/src/main/java/app/revanced/integrations/twitter/patches/links/ChangeLinkSharingDomainPatch.java
Integrations for https://github.com/ReVanced/revanced-patches/pull/3753
> feat(Twitter): Add `Change link sharing domain` patch
